# **About Dataset**
**Context This is a small subset of dataset of Book reviews from Amazon Kindle Store category.**

Content 5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset. Columns

asin - ID of the product, like B000FA64PK
helpful - helpfulness rating of the review - example: 2/3.
overall - rating of the product.
reviewText - text of the review (heading).
reviewTime - time of the review (raw).
reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
reviewerName - name of the reviewer.
summary - summary of the review (description).
unixReviewTime - unix timestamp.
Acknowledgements This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

Inspiration

  * Sentiment analysis on reviews.
  * Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
  * Fake reviews/ outliers.
  * Best rated product IDs, or similarity between products based on  reviews alone (not the best idea ikr).
  * Any other interesting analysis

In [ ]:
import pandas as pd

In [ ]:
# loading of the dataset
data=pd.read_csv('/content/all_kindle_review.csv')
data.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [ ]:
data=data[['reviewText', 'rating']]

In [ ]:
data.shape

(12000, 2)

In [ ]:
## missing values
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [ ]:
data['rating'].unique()

array([3, 5, 4, 2, 1])

In [ ]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

**Preprocessing & cleaning**

In [ ]:
## positive review as 1 and negative review as no
data['rating']=data['rating'].apply(lambda x : 0 if x <3 else 1)

In [ ]:
data['rating']

0        1
1        1
2        1
3        1
4        1
        ..
11995    1
11996    1
11997    1
11998    0
11999    1
Name: rating, Length: 12000, dtype: int64

In [ ]:
data['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [ ]:
## 1. Lower all the cases
data['reviewText']=data['reviewText'].str.lower()

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
## 2. removing special characters
data['reviewText']=data['reviewText'].apply(lambda x:re.sub(r'[^a-z A-Z 0-9]+', '', x))
## removing the stopwords
data['reviewText']=data['reviewText'].apply(lambda x: " ".join([y for y in x.split() if y not in stopwords.words('english') ]))
## removing urls
data['reviewText']=data['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))

##remove html tags
data['reviewText']=data['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
data['reviewText']=data['reviewText'].apply(lambda x: " ".join(x.split()))

In [ ]:
data.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [ ]:
## Lemmatize the word into lemma
from nltk.stem import WordNetLemmatizer

In [ ]:
lemmtizer=WordNetLemmatizer()

In [ ]:
def lemmatize_words(text):
  return " ".join([lemmtizer.lemmatize(word) for word in text.split()])

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
data['reviewText']=data['reviewText'].apply(lambda text: lemmatize_words(text))

In [ ]:
data.head()

                                          reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [ ]:
## Train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data['reviewText'], data['rating'], test_size=0.20)

In [ ]:
X_train

11807    shifter love story great book loved one maya b...
470      ok seriously frustrating book ever read believ...
8304     love lilas story ive read monster book fresh d...
846      book total disappointment basically went like ...
8686     wonderful way read way older woman investigate...
                               ...
4378     feel book displaying type abuse never called r...
11628    lady amelia secret lover delightful short stor...
9435     way short well written hot steamy wish longer ...
2428     hunter jericho share cabin high rocky mountain...
8243     maia rylan short story book one two tale share...
Name: reviewText, Length: 9600, dtype: object

In [ ]:
X_test

10635    ive liked author story cause mix erotic advent...
5503     ok book slow time actually put read something ...
5363     enjoyed henry wright mystery plot good well wr...
6548     dont much say angel pawn liked didnt love mayb...
11036    story kept funny reminded movie local hero vil...
                               ...
10429    good book plot developed character lovable bad...
7347     really liked book character welldeveloped stor...
1065     reader may bit picky write story based upon pr...
880      book overall eh steamy sex scene felt characte...
428      wasnt bad read simple short like twist book we...
Name: reviewText, Length: 2400, dtype: object

In [ ]:
y_train

11807    1
470      0
8304     1
846      0
8686     1
        ..
4378     0
11628    1
9435     1
2428     1
8243     1
Name: rating, Length: 9600, dtype: int64

**BOW embedding**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

**TF-TDF embedding**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

**Word2Vec embedding**

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 29.9 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
tokenized_reviews_train = X_train.apply(lambda x: x.split())
tokenized_reviews_test = X_test.apply(lambda x: x.split())

In [ ]:
word2vec_model = gensim.models.Word2Vec(
    sentences=tokenized_reviews_train,
    vector_size=100,
    window=5,
    min_count=1,
    sg=0
)

In [ ]:
def get_word2vec_embeddings(text_list, model):
    vectors = []
    for word in text_list:
        if word in model.wv:
            vectors.append(model.wv[word])
    if vectors:
        return sum(vectors) / len(vectors)
    else:
        return [0.0] * model.vector_size

In [ ]:
X_train_word2vec = tokenized_reviews_train.apply(lambda x: get_word2vec_embeddings(x, word2vec_model))
X_test_word2vec = tokenized_reviews_test.apply(lambda x: get_word2vec_embeddings(x, word2vec_model))

In [ ]:
X_train_word2vec = pd.DataFrame(X_train_word2vec.tolist())
X_test_word2vec = pd.DataFrame(X_test_word2vec.tolist())

In [ ]:
print('X_train_word2vec shape:', X_train_word2vec.shape)
print('X_test_word2vec shape:', X_test_word2vec.shape)

display(X_train_word2vec.head())
display(X_test_word2vec.head())

X_train_word2vec shape: (9600, 100)
X_test_word2vec shape: (2400, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.720139,0.389957,0.026456,0.119683,0.247663,-1.515620,0.668258,1.493219,-0.783436,-0.387658,...,0.918938,0.516819,0.585178,-0.007884,1.102696,0.906647,0.528627,-0.713313,0.096707,0.104522
1,-0.341228,0.570731,0.265800,0.261582,0.073942,-0.880655,0.474898,1.205862,-0.635389,-0.655205,...,0.877930,0.500984,0.282879,0.006388,0.916039,0.939628,0.326272,-0.692958,0.223931,-0.164476
2,-0.486041,0.557517,0.205798,0.026323,0.144616,-1.076425,0.436993,1.274084,-0.587097,-0.552317,...,0.770818,0.566003,0.349980,-0.066123,1.087971,0.918048,0.465837,-0.726848,0.239086,-0.037766
3,-0.320848,0.237145,0.241532,0.432651,0.083128,-0.970271,0.446408,1.085658,-0.389881,-0.369608,...,0.811707,0.327194,-0.019785,0.182418,1.142197,0.788978,0.089387,-0.621121,-0.068431,-0.103189
4,-0.498074,0.341146,0.202907,0.289441,0.199946,-1.106387,0.461941,1.177702,-0.594010,-0.417168,...,0.748784,0.375744,0.239792,0.088625,1.100598,0.813190,0.332988,-0.621420,-0.004356,-0.053718

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.403063,0.384348,-0.007167,0.254798,0.310458,-1.198453,0.611780,1.293560,-0.415258,-0.293313,...,0.815951,0.393130,0.493878,-0.028950,1.029138,1.111710,0.417931,-0.652706,0.112652,-0.060808
1,-0.398756,0.510988,0.391436,0.489639,0.050793,-1.100016,0.527219,1.557931,-0.835922,-0.794799,...,1.154902,0.602940,0.348552,-0.027696,0.955189,0.963958,0.418234,-0.759929,0.056209,-0.248760
2,-0.511192,0.477243,-0.000834,0.058840,0.290677,-1.485981,0.784440,1.703568,-0.780278,-0.662799,...,1.157017,0.712782,0.924651,-0.067739,0.915828,1.271199,0.575233,-1.007634,0.559117,-0.207677
3,-0.468629,0.331469,0.086564,0.363551,0.183571,-1.124650,0.597221,1.191860,-0.565987,-0.367347,...,0.961995,0.497752,0.290842,0.118247,0.931931,0.881499,0.258411,-0.707702,0.091360,-0.176683
4,-0.277870,0.296711,0.108111,0.293891,0.189899,-0.997536,0.467135,1.150602,-0.517758,-0.525430,...,0.924887,0.399633,0.358924,-0.030454,0.812604,0.844177,0.264749,-0.588167,0.020565,-0.095497

In [ ]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_test_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# **NaiveBayes model**

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [ ]:
y_pred_bow=nb_model_bow.predict(X_test_bow)

In [ ]:
y_pred_tfidf=nb_model_tfidf.predict(X_test_tfidf)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
print("BOW accuracy",accuracy_score(y_test, y_pred_bow))

BOW accuracy 0.57625

In [ ]:
confusion_matrix(y_test,y_pred_bow)

array([[519, 283],
       [734, 864]])

In [ ]:
print("TF-TDF accuracy",accuracy_score(y_test, y_pred_tfidf))

TF-TDF accuracy 0.5783333333333334

In [ ]:
confusion_matrix(y_test,y_pred_tfidf)

array([[508, 294],
       [718, 880]])

# **Word2Vec embedding**

In [ ]:
nb_model_word2vec = GaussianNB().fit(X_train_word2vec, y_train)

In [ ]:
y_pred_word2vec = nb_model_word2vec.predict(X_test_word2vec)

In [ ]:
print("Word2Vec accuracy", accuracy_score(y_test, y_pred_word2vec))

Word2Vec accuracy 0.6654166666666667

In [ ]:
print("Confusion Matrix for Word2Vec:\n", confusion_matrix(y_test, y_pred_word2vec))

Confusion Matrix for Word2Vec:
 [[615 187]
 [616 982]]